//tealium universal tag - utag.1088 ut4.0.202107081857, Copyright 2021 Tealium.com Inc. All Rights Reserved.
var _tvq=_tvq||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":0};u.initialized=false;u.scriptrequested=false;u.map={"cp.utag_main_v_id":"user_ref,action_id"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"//collector-##CLIENT_ID##.tvsquared.com/","client_id":"1564","brand_id":"TV-81453654-1","tracker_type":"action","action_name":"hulureturningusers"};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.action_id=u.data.action_id||b._corder||"";u.data.revenue=u.data.revenue||b._csubtotal||"0";u.data.promocode=u.data.promocode||b._cpromo||"";if(u.data.product===undefined&&b._ccat!==undefined&&u.typeOf(b._ccat)=="array")
u.data.product=b._ccat.slice(0)[0];_tvq.push(["setSiteId",u.data.brand_id]);_tvq.push(["setTrackerUrl",u.data.base_url.replace("##CLIENT_ID##",u.data.client_id)+"tv2track.php"]);if(u.data.tracker_type=="action"){_tvq.push([function(){this.setCustomVariable(5,"session",JSON.stringify({"user":u.data.user_ref}),"visit");}]);_tvq.push([function(){this.setCustomVariable(5,u.data.action_name,JSON.stringify({"rev":u.data.revenue,"prod":u.data.product,"id":u.data.action_id,"promo":u.data.promocode}),"page");}]);}
_tvq.push(["trackPageView"]);if(u.data.tracker_type=="action")
_tvq.push(["enableLinkTracking"]);u.loader_cb=function(){u.initialized=true;};if(u.initialized){u.loader_cb(a,b,c);}else{if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url.replace("##CLIENT_ID##",u.data.client_id)+"tv2trackext.js","cb":u.loader_cb,"loc":"script","id":'utag_1088'});}}
}};utag.o[loader].loader.LOAD(id);}("1088","hulu.main"));}catch(error){utag.DB(error);}
